#!/usr/bin/env python3

import sys
import base64
import codecs

def encode(bytesin):
    return base64.b64encode(codecs.encode(bytesin, 'hex')).decode('utf-8')

if __name__ == '__main__':
    buf = sys.stdin.buffer.read()
    sys.stdout.write(encode(buf))
