services:
  exnux:
    container_name: "exnux"
    build: "."
    cap_add:
      - SYS_PTRACE # Required for strace
      - NET_ADMIN # for WireShark
    privileged: true # required for network access
    stdin_open: true # -i
    tty: true # -t
    network_mode: "host" # YOLO. Network is not isolated.
    shm_size: "2gb" # for chromium
    environment:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      DISPLAY: "${DISPLAY}" # X11
      XAUTHORITY: "${XAUTHORITY}" # X11
      _JAVA_OPTIONS: "${_JAVA_OPTIONS}" # for JAVA scaling issues (_JAVA_OPTIONS="-Dsun.java2d.uiScale=2.0" in .env to scale UI)
      TERM: "${TERM}" # for tmux
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/1000/bus" # for DBUS
      XDG_RUNTIME_DIR: "/run/user/1000"
    volumes:
      # Mount x11, docker, and dbus socket
      - "${XAUTHORITY}:/home/${USERNAME}/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${XDG_RUNTIME_DIR}/bus:/run/user/1000/bus"
      - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
      - "${XDG_RUNTIME_DIR}/pulse:/run/user/1000/pulse"

      # Mount home directory
      - "/:/home/${USERNAME}/root"
      - "${HOME}:/home/${USERNAME}/home"
      - "${HOME}/.ssh:/home/${USERNAME}/.ssh"
      - "${HOME}/Downloads:/home/${USERNAME}/Downloads"
      - "${HOME}/Documents:/home/${USERNAME}/Documents"
      - "${HOME}/Pictures:/home/${USERNAME}/Pictures"

      # Mount command history
      - "./cache/.cache/zsh/:/home/${USERNAME}/.cache/zsh/"
      - "./cache/.cache/gdb/:/home/${USERNAME}/.cache/gdb/"
      - "./cache/.bash_history:/home/${USERNAME}/.bash_history"
      - "./cache/.cache/radare2/history:/home/${USERNAME}/.cache/radare2/history"
      - "./cache/.msf4/history:/home/${USERNAME}/.msf4/history"
      - "./cache/nvim:/home/${USERNAME}/.cache/nvim"

      # Mount other directories
      - "./cache/mytags:/home/${USERNAME}/.config/nvim/ctags/mytags"
      - "./cache/.config/github-copilot/hosts.json:/home/${USERNAME}/.config/github-copilot/hosts.json"
      - "./cache/.config/chromium:/home/${USERNAME}/.config/chromium"
      - "./cache/treesitter/parser:/home/${USERNAME}/.config/nvim/bundle/nvim-treesitter/parser/"
      - "./cache/treesitter/parser-info:/home/${USERNAME}/.config/nvim/bundle/nvim-treesitter/parser-info/"
      - "./cache/.config/lazygit:/home/${USERNAME}/.config/lazygit/"
      - "./cache/.msf4/db/:/home/postgres/msf-postgres/"
    devices:
      - "/dev/dri" # GPU
      - "/dev/snd" # Sound
      - "/dev/video0:/dev/video0" # Webcam
    command: "/usr/local/src/scripts/entrypoint.sh"
  apt-cacher-ng:
    container_name: "apt-cacher-ng"
    image: "sameersbn/apt-cacher-ng:3.3-20200524"
    volumes:
      - "/srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng"
    ports:
      - "172.17.0.1:3142:3142"

