#!/bin/bash
CMD="$1"
# Use buildkit (allows you to build stages in parallel)
export DOCKER_BUILDKIT=1

#Ensure home variable is set
export HOME=${HOME:-/root}

# Ensure DISPLAY and XAUTHORITY are set, if not just guess
export XAUTHORITY=${XAUTHORITY:-$HOME/.Xauthority}
export DISPLAY=${DISPLAY:-}

# This is the username from the Dockerfile
export USERNAME=nonroot

# Find this scripts location
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

CACHE_DIR_LIST="/cache /cache/nvim /cache/nvim/swp /cache/nvim/undo /cache/mytags /cache/.cache/radare2 /cache/treesitter/ /cache/treesitter/parser /cache/treesitter/parser-info /cache/.msf4 /cache/.config/github-copilot /cache/.config/chromium /cache/.config/lazygit /cache/.config/zsh /cache/.config/gdb"
CACHE_FILE_LIST="/cache/.bash_history /cache/.cache/radare2/history /cache/.msf4/history /cache/.config/github-copilot/hosts.json"


case "$CMD" in
    init)
        sudo apt-get install docker.io git curl
        sudo curl -SL https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    ;;
    build)
        docker-compose build exnux
    ;;
    build-apt-cache)
        docker-compose up -d apt-cacher-ng
        sleep 5 # Wait for apt-cacher-ng to start
        docker-compose build --build-arg APT_PROXY="http://172.17.0.1:3142" exnux
        docker-compose stop apt-cacher-ng
    ;;
    start-headless)

        # Create all the cache directories and files (to prevent these being owned by root)
        for CACHE_DIR in $CACHE_DIR_LIST; do
            mkdir -p $SCRIPT_DIR/$CACHE_DIR
        done
        for CACHE_FILE in $CACHE_FILE_LIST; do
            touch -a $SCRIPT_DIR/$CACHE_FILE
        done

        docker-compose up --no-recreate -d exnux
        docker-compose exec -T -u "0:0" exnux groupmod -g $(getent group docker | awk -F: '{print $3}') docker

        # Change uid and gid to match host os
        docker-compose exec -T -u "0:0" exnux usermod -u $(id -u) $USERNAME
        #TODO: This breaks things
        #docker-compose exec -T -u "0:0" exnux groupmod -g $(id -g) $USERNAME

    ;;
    start)
        $0 start-headless
        docker-compose exec -e TERM=${TERM} exnux /usr/bin/byobu
    ;;
    start-gui)
        $0 start-headless
        docker-compose exec -d exnux alacritty --command byobu
    ;;
    clean)
        docker-compose rm -s -f
    ;;
    pull)
        git stash
        git pull --rebase origin master
        git submodule update --init --recursive
        git stash pop
    ;;
    distclean)
        $0 clean
        git stash
        git clean -fdx :dotfiles
        git reset --hard origin/master
    ;;
    disinfect)
        rm -rf /usr/local/src/exnux
        rm -f /usr/local/bin/exnux
    ;;
    *)
        echo $0 [COMMAND]
        echo ""
        echo -e "Commands:\n" \
            "  init             install necessary packages (git, docker, docker-compose)\n" \
            "  build            Builds container image\n" \
            "  build-apt-cache  Builds container image with an apt-cacher-ng proxy server\n" \
            "  start            Starts exnux tmux in current shell\n" \
            "  start-gui        Starts exnux tmux in alacritty\n" \
            "  pull             Updates the repo from origin/master and initializes submodules\n" \
            "  clean            Stops all containers\n" \
            "  distclean        Tries to restore files to a fresh state\n" \
            "  start-headless   Starts exnux in the background\n" \
            "  disinfect        Removes exnux from the system installed from infect\n" \
            "  help             This help message\n"
    ;;
esac
