add-apt-repository ppa:ansible/ansible \
    && apt-get update -y \
    && apt-get install -y \
      `# ghidra` \
        fontconfig \
        libc-dbg:i386 \
        libc6-dbg \
        libglib2.0-dev \
        libxi6 \
        libxrender1 \
        libxtst6 \
        openjdk-17-jdk \
        openjdk-17-jre \
       `# iaito` \
        libgvc6 \
        libqt5svg5 \
        libuuid1 \
        qt5-default \
      `# alacritty` \
        cmake \
        libfontconfig1-dev \
        libfreetype6-dev \
        libxcb-xfixes0-dev \
        libxkbcommon-dev \
        pkg-config \
        python3 \
      `# BeEF` \
        curl \
        git \
        build-essential \
        openssl \
        libreadline6-dev \
        zlib1g \
        zlib1g-dev \
        libssl-dev \
        libyaml-dev \
        libsqlite3-0 \
        libsqlite3-dev \
        sqlite3 \
        libxml2-dev \
        libxslt1-dev \
        autoconf \
        libc6-dev \
        libncurses5-dev \
        automake \
        libtool \
        bison \
       `# nodejs` \
        libcurl4-openssl-dev \
        gcc-9-base \
        libgcc-9-dev \
      `# pwninit` \
        liblzma-dev \
      `# gimp` \
        gtk2-engines-pixbuf \
        libcanberra-gtk-module \
      `# large` \
        audacity \
        clangd \
        docker.io \
        firefox \
        gimp \
        hashcat \
        hashcat-nvidia \
        inkscape \
        mysql-client \
        nmap \
        okular \
        smbclient \
        sqlmap \
        wireshark \
      `# everything else` \
        alsa-base \
        alsa-utils \
        ansible \
        apktool \
        apulse \
        autopsy \
        bash-completion \
        binutils \
        binwalk \
        byobu \
        cpio \
        dc \
        dialog \
        dnsutils \
        elfutils \
        exiftool \
        expect \
        exuberant-ctags \
        fd-find \
        ffmpeg \
        flake8 \
        fonts-beng \
        fonts-dejavu \
        fonts-deva \
        fonts-freefont-ttf \
        fonts-gujr \
        fonts-guru \
        fonts-indic \
        fonts-knda \
        fonts-liberation \
        fonts-mlym \
        fonts-noto-cjk \
        fonts-noto-color-emoji \
        fonts-opensymbol \
        fonts-orya \
        fonts-smc \
        fonts-taml \
        fonts-telu \
        fonts-ubuntu \
        fonts-ubuntu-console \
        fonts-ubuntu-title \
        foremost \
        ftp \
        git-gui \
        gitk \
        htop \
        hydra \
        iputils-ping \
        jq \
        ldap-utils \
        libclang-9-dev \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        libsndfile1-dev \
        ltrace \
        lz4 \
        lzip \
        lzop \
        nasm \
        ncat \
        net-tools \
        netcat-openbsd \
        nfs-common \
        nikto \
        openssh-client \
        openvpn \
        ophcrack \
        p0f \
        parallel \
        patchelf \
        postgresql-client \
        pv \
        python3-venv \
        ripgrep \
        sleuthkit \
        snmp \
        socat \
        strace \
        tcpdump \
        tmux \
        virt-manager \
        x2goclient \
        xclip \
        xxd \
        zsh
