vim.cmd("call pathogen#infect()")
require('ex_lsp')
require('ex_copilot')
require('ex_ls')
require('ex_cmp')
require('ex_ts')
require('ex_dap')
require('ex_telescope')
require('ex_colorpicker')
require('ex_leap')
require('ex_clipboard')
require('ex_lualine')
