#!/usr/bin/env python3

import sys
import codecs

def encode(bytesin):
    return codecs.encode(bytesin, 'hex').decode('ascii')

if __name__ == '__main__':
    while True:
        buf = sys.stdin.buffer.read(1024)
        if not buf:
            break
        sys.stdout.write(encode(buf))
