#!/usr/bin/env python3

import sys
import codecs

def encode(hexin):
    return codecs.decode(hexin, 'hex')


if __name__ == '__main__':
    while True:
        buf = sys.stdin.buffer.read(1024)
        if not buf:
            break
        sys.stdout.buffer.write(encode(buf))
